export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS ';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
export const OPENED_MORE_INFO = 'OPENED_MORE_INFO';
export const CLOSED_MORE_INFO = 'CLOSED_MORE_INFO';
export const TO_PREV_PAGE = 'TO_PREV_PAGE';
export const TO_NEXT_PAGE = 'TO_NEXT_PAGE';
export const TO_NUM_PAGE = 'TO_NUM_PAGE';
